add docker lib
wizaplace/bash-lib pull request #1
Opened 2019-08-08 06:39 UTC by philippe-vandermoere

2019-08-08 06:48 UTC, jeremy-wizaplace requested changes

2019-08-08 06:48 UTC, jeremy-wizaplace commented on README.md
> +Provide bash function for Wizaplace's projects
```suggestion
Provide bash functions for Wizaplace's projects
```

2019-08-08 07:02 UTC, steevanb requested changes

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +readonly RESET='\033[0;0m'
je n'ai jamais compris la différence entre `\e` et `\033` ?

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +function check_version () {
```suggestion
function check_version() {
```

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +        || (echo -e "${RED}Requirement: need '${package}:${require_version}', you are '${package}:${version}'." && exit 1)
```suggestion
        || (echo -e "${RED}Requirement: need '${package}:${require_version}', you have '${package}:${version}'." && exit 1)
```

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +        echo -e "${RED}Requirement: need 'docker:${DOCKER_MINIMAL_VERSION}' see https://docs.docker.com/install/linux/docker-ce/ubuntu ."
ça foire le lien si on met le `.` collé au lien ?
```suggestion
        echo -e "${RED}Requirement: need 'docker:${DOCKER_MINIMAL_VERSION}' see https://docs.docker.com/install/linux/docker-ce/ubuntu."
```

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +        echo -e "${RED}Requirement: need 'docker-compose:${DOCKER_COMPOSE_MINIMAL_VERSION}' see https://docs.docker.com/compose/install ."
ça foire le lien si on met le `.` collé au lien ?
```suggestion
        echo -e "${RED}Requirement: need 'docker-compose:${DOCKER_COMPOSE_MINIMAL_VERSION}' see https://docs.docker.com/compose/install."
```

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +        echo -e "${RED}Requirement: need 'jq' try 'sudo apt install jq' ."
```suggestion
        echo -e "${RED}Requirement: need 'jq' try 'sudo apt install jq'."
```

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +        echo -e "${RED}The environment '${env}' does not exit."
on pourrait préciser quel répertoire est à créer ?

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +    local env_dist_file="${1}/.env.dist"
```suggestion
    local env_dist_file="${directory}/.env.dist"
```

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +        for line in $(cat ${env_dist_file}); do
il me semble que le séparateur par défaut est espace, si on fait ça on ne va pas avoir des lignes qui n'en sont pas ? exemple `ENV_VAR="foo bar"` ?

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +    local value
c'est une façon de définir toutes les variables en haut d'une fonction, et d'assigner leur valeur plus tard ?

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +    echo "${key}=${value}" >> ${env_file}
si j'ai bien compris, on va faire cet echo dans tous les cas, même si la variable existe déjà dans le fichier `${env_file}`. ça risque de faire des doublons dans le fichier non ?

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +    local current_directory=$(pwd)
on n'avait pas vu que la meilleure façon de récupérer le répertoire est `$(realpath $(dirname $(realpath $0)))` ?

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +    local options=${2}
je vois l'utilisation de ${x} et $x pour récupérer les variables. est-ce que ça a un intérêt bien précis de ne pas le faire tout le temps ? quel est l'avantage de le faire déjà ?

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +    local current_directory=$(pwd)
pareil que plus haut pour récupérer le chemin courant

2019-08-08 07:02 UTC, steevanb commented on lib/docker.sh
> +    cd ${current_directory}
on pourrait utiliser `docker-compose -f ${directory}/docker-compose.yml` pour éviter de faire 2 `cd` ?

2019-08-08 07:05 UTC, philippe-vandermoere commented on lib/docker.sh
> +    cd ${current_directory}
il prend le fichier .env du dossier courant si tu fais cette commande

2019-08-08 07:07 UTC, philippe-vandermoere commented on lib/docker.sh
> +    local current_directory=$(pwd)
cela donne le directory du script, pas l'endroit ou se trouve l'utilisateur quand il lance la commane

2019-08-08 07:07 UTC, philippe-vandermoere commented on lib/docker.sh
> +    local current_directory=$(pwd)
voir plus haut

2019-08-08 07:08 UTC, philippe-vandermoere commented on lib/docker.sh
> +    local options=${2}
${x} permet d'utiliser du posix sur la variable, pas utilise dans le cas

2019-08-08 07:09 UTC, philippe-vandermoere commented on lib/docker.sh
> +    echo "${key}=${value}" >> ${env_file}
non car le sed au dessus supprime la ligne de la clé si elle existe

2019-08-08 07:11 UTC, philippe-vandermoere commented on lib/docker.sh
> +        echo -e "${RED}Requirement: need 'docker-compose:${DOCKER_COMPOSE_MINIMAL_VERSION}' see https://docs.docker.com/compose/install ."
le lien n'est plus bon si je colle le point à l'url

2019-08-08 07:11 UTC, philippe-vandermoere commented on lib/docker.sh
> +        echo -e "${RED}Requirement: need 'docker:${DOCKER_MINIMAL_VERSION}' see https://docs.docker.com/install/linux/docker-ce/ubuntu ."
le lien n'est plus bon si je colle le point à l'url

2019-08-08 07:12 UTC, philippe-vandermoere commented on lib/docker.sh
> +        echo -e "${RED}The environment '${env}' does not exit."
pas certain que c'est le rôle de cette function

2019-08-08 07:13 UTC, philippe-vandermoere commented on lib/docker.sh
> +readonly RESET='\033[0;0m'
pareil

2019-08-08 07:17 UTC, jeremy-wizaplace approved these changes
J'approuve ma demande de modif

2019-08-08 07:24 UTC, Nicolas-Masson-Wizaplace commented on lib/docker.sh
> +    if [[ "$(which docker-compose)" == "" ]]; then
Ah tiens, p'tite alternative pour vérifier la présence d'un programme avec `hash`
```bash
hash ton_programme 2>&1 && echo 'ton_programme existe'
# ou
hash ton_programme 2>&1 || echo 'ton_programme existe pas'
```

2019-08-08 07:24 UTC, Nicolas-Masson-Wizaplace commented on lib/docker.sh
> +    check_version $(docker -v | sed 's/,//'| awk '{print $3}') ${DOCKER_MINIMAL_VERSION} 'docker'
```suggestion
    check_version $(docker -v | sed -r 's/.* version ([^,]+),.*/\1/') ${DOCKER_MINIMAL_VERSION} 'docker'
```

sed only :P

2019-08-09 06:17 UTC, philippe-vandermoere commented on lib/docker.sh
> +    local value
c'est équivalent à local value=""

2019-08-09 06:17 UTC, philippe-vandermoere commented on lib/docker.sh
> +        for line in $(cat ${env_dist_file}); do
bien vue

2019-08-09 07:04 UTC, cyprille commented on lib/docker.sh
> +    local options=${2}
@philippe-vandermoere ah bon ? pour moi c'était pour pouvoir identifier clairement la variable et faire de la concaténation. 

Par exemple : 

```
var="foo"

echo $varbar // N'affiche rien
echo ${var}bar // Affiche foobar
```

2019-08-09 07:36 UTC, philippe-vandermoere commented on lib/docker.sh
> +    local options=${2}
ça permet de faire la concaténation mais pas que, voici des exemples
http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02

2019-08-09 07:40 UTC, cyprille requested changes

2019-08-09 07:40 UTC, cyprille commented on lib/docker.sh
> +readonly RESET='\033[0;0m'
- \033 est la valeur octal de l'échappement
- \e est l'escape sequence de l'échappement

Donc c'est la même façon de représenter la valeur.
Si tu codais en binaire, tu pourrais utiliser `001 1011` :p

https://en.wikipedia.org/wiki/ASCII

2019-08-09 07:40 UTC, cyprille commented on lib/docker.sh
> +    if [[ "$(which docker-compose)" == "" ]]; then
@Nicolas-Masson-Wizaplace pour le coup je préfère la méthode utilisée par @philippe-vandermoere qui est plus courte et plus facile à comprendre :)

2019-08-09 07:40 UTC, cyprille commented on lib/docker.sh
> +    check_version $(docker-compose -v | sed 's/,//'| awk '{print $3}') ${DOCKER_COMPOSE_MINIMAL_VERSION} 'docker-compose'
C'est plus lisible d'avoir un espace avant et après le pipe :)

`    check_version $(docker-compose -v | sed 's/,//' | awk '{print $3}') ${DOCKER_COMPOSE_MINIMAL_VERSION} 'docker-compose'`

2019-08-09 07:40 UTC, cyprille commented on lib/docker.sh
> +    local env_file=$1
Je ne comprends pas l'usage de la déclaration de `env_file` qui n'est jamais transformée.
Il serait donc préférable d'utiliser directement $1 non ?
Ou alors c'est fait volontairement pour faciliter le futur changement éventuel d'ordre des paramètres du script ?

2019-08-09 07:40 UTC, cyprille commented on lib/docker.sh
> +    echo ${value}
Ici `$value` peut être null donc cela n'affichera rien si l'on ne passe pas dans un des cas du case.
Ne devrait-il pas y avoir une valeur par défaut ?

2019-08-09 07:40 UTC, cyprille commented on lib/docker.sh
> +    local host=$1
Même remarque que plus haut, la définition de la variable `$host` pourrait être supprimée.
Si c'est pour une question de visibilité et de compréhension des paramètres, il serait préférable de définir ces variables avec une portée globale sur le fichier (donc tout en haut).

2019-08-09 07:48 UTC, philippe-vandermoere commented on lib/docker.sh
> +    local env_file=$1
J'ai l'habitude de nommer les paramètres dans les function bash pour une meilleur visibilité
et c'est plus simple quand tu change l'ordre des paramètre

2019-08-09 08:07 UTC, philippe-vandermoere commented on lib/docker.sh
> +    echo ${value}
c'est voulu, cela signifie que ce n'est pas une valeur calculer

2019-08-09 08:10 UTC, cyprille approved these changes

2019-08-09 08:34 UTC, merged